#!/bin/bash
dest="$1"

if [[ -z "$dest" ]]; then
  dest="bundle.go"
fi

echo -e "package main\n\n// this file is auto-generated by bundle.sh\n" > $dest

function bundleDir {
  for f in $1/*; do
    bundleFile $f
  done
}

function bundleFile {
  echo -ne "\t\"$1\": \`" >> $dest
  cat $1 |base64 >> $dest
  echo -ne "\`,\n" >> $dest
}

echo "var _bundle = map[string]string{" >> $dest

bundleDir templates
bundleDir static/css
bundleDir static/js
bundleDir static/fonts
bundleFile goiki.toml

echo -e "}\n" >> $dest