#
# Goiki Configuration
#

# The name of the wiki; this is used in the packaged templates provided by Goiki
name = "Goiki"

# Hostname or IP address the webserver will listen on
host = "0.0.0.0"

# Port number the webserver will bind to
port = 4567

# Path to data files (the Git repo)
data_dir = "./data"

# Name of page to use for the index of a category (or directory)
index_page = "home"

# File extension to use within the filesystem
file_extension = "md"

# Theme to use with default templates; see http://bootswatch.com for details.
# Valid values are: "default", "cerulean", "cosmo", "cyborg", "darkly", "flatly",
# "journal", "lumen", "paper", "readable", "sandstone", "simplex", "slate",
# "spacelab", "superhero", "united" and "yeti"
theme = "default" 

# Path to custom templates; leave empty to use the packaged templates
template_dir = ""

# Path to static content; leave empty to use the packaged content
static_dir = ""

# CSS class(es) to use for tables
table_class = "table table-striped table-hover"

# Wiki users.
#
# Each user entry must provide a `name`, `email`, `username` and `password`.
# `name` and `email` are used for Git commits, while `username` and
# `password` are used for authenticating over HTTP.
#
# Passwords can be generated using `htpasswd`. Both MD5 and SHA1 passwords
# are supported. 
#
# Repeat the [[users]] section for additional users.
[[users]]
name = "Goiki"
email = "goiki@example.com"
username = "goiki"
password = "{SHA}4v0+mLtvlX3qyy5ISrQU5mw0Yhg="
